from fastapi import APIRouter, Depends, HTTPException, Query, UploadFile, File
from sqlalchemy.orm import Session
from sqlalchemy.exc import IntegrityError
from app.core.database import get_db
from app.core.dependencies import get_current_user
from app.models.models import (
    Vehicle,
    Document,
    Loan,
    EMI,
    Challan,
    RoadTax,
    Notification,
    Setting,
    AuditLog,
)
from app.utils.serialize import (
    vehicle_out,
    document_out,
    loan_out,
    emi_out,
    challan_out,
    roadtax_out,
)
from datetime import datetime, timezone, date
import calendar
import math
import re

router = APIRouter(prefix="/api/v1", tags=["Fleet"])

MODEL_MAP = {
    "vehicles": Vehicle,
    "documents": Document,
    "loans": Loan,
    "emis": EMI,
    "challans": Challan,
    "road-taxes": RoadTax,
}

SERIAL = {
    "vehicles": vehicle_out,
    "documents": document_out,
    "loans": loan_out,
    "emis": emi_out,
    "challans": challan_out,
    "road-taxes": roadtax_out,
}

ACTION_MODULE = {
    "vehicles": "vehicles",
    "documents": "documents",
    "loans": "emi",
    "emis": "emi",
    "challans": "challans",
    "road-taxes": "roadTax",
}


# ============================================================
# PERMISSION
# ============================================================

def allowed(user, collection, action, db=None):
    if user.role == "Admin":
        return True

    perms = user.permissions or {}
    module = ACTION_MODULE[collection]

    if isinstance(perms.get(module), dict) and perms[module].get(action):
        return True

    if isinstance(perms.get(collection), dict) and perms[collection].get(action):
        return True

    role_block = perms.get(user.role)
    if isinstance(role_block, dict) and role_block.get(action):
        return True

    if db is not None:
        s = db.query(Setting).filter(Setting.key == "global").first()
        rp = (s.value or {}).get("rolePermissions", {}) if s else {}
        role_block = rp.get(user.role, {})

        if isinstance(role_block, dict) and role_block.get(action):
            return True

    return False


# ============================================================
# GENERAL PAYLOAD CLEANING
# ============================================================

def clean_payload(payload, model):
    payload = dict(payload or {})

    aliases = {
        "contactNo": "phone",
        "challanNo": "challan_no",
        "taxType": "tax_type",
        "fileName": "file_name",
        "fileUrl": "file_url",
        "loanId": "loan_id",
        "paidDate": "paid_date",
        "monthlyAmount": "monthly_amount",
        "interestRate": "interest_rate",
        "tenureMonths": "tenure_months",
        "startDate": "start_date",
        "closingDate": "closing_date",
    }

    for alias, column in aliases.items():
        if alias in payload and column not in payload:
            payload[column] = payload.pop(alias)

    known = set(model.__table__.columns.keys())

    extra = {
        key: value
        for key, value in payload.items()
        if key not in known
    }

    data = dict(payload.get("data") or {})
    data.update(extra)

    # Primary keys are generated by the database.
    # The frontend may send an ``id`` (often a JavaScript timestamp),
    # but PostgreSQL stores these IDs as INTEGER. A millisecond timestamp
    # such as 1790597243881 is far outside the INTEGER range and causes:
    #   psycopg2.errors.NumericValueOutOfRange: integer out of range
    #
    # Therefore, never accept a client-supplied id during CREATE.
    # SQLAlchemy/PostgreSQL will generate the next valid integer ID.
    payload = {
        key: value
        for key, value in payload.items()
        if key in known and key not in {"data", "id"}
    }

    if "data" in known:
        payload["data"] = data

    return payload


# ============================================================
# DATE / NUMBER HELPERS
# ============================================================

def _to_float(value, default=0.0):
    if value is None or value == "":
        return default

    if isinstance(value, bool):
        return float(value)

    try:
        if isinstance(value, str):
            value = value.replace(",", "").replace("₹", "").strip()

        return float(value)
    except (TypeError, ValueError):
        return default


def _to_int(value, default=0):
    if value is None or value == "":
        return default

    try:
        return int(float(str(value).strip()))
    except (TypeError, ValueError):
        return default


def _parse_date(value):
    """
    Accept the date formats commonly used by FleetDoc.

    Examples:
        2026-07-10
        10-07-2026
        10/07/2026
        10.07.2026
        10 Jul 2026
        10 July 2026
    """

    if value is None:
        return None

    if isinstance(value, datetime):
        return value.date()

    if isinstance(value, date):
        return value

    text = str(value).strip()

    if not text:
        return None

    # ISO datetime, e.g. 2026-07-10T00:00:00
    if "T" in text:
        text = text.split("T", 1)[0]

    formats = (
        "%Y-%m-%d",
        "%d-%m-%Y",
        "%d/%m/%Y",
        "%d.%m.%Y",
        "%d %b %Y",
        "%d %B %Y",
        "%Y/%m/%d",
    )

    for fmt in formats:
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            continue

    return None


def _date_to_iso(value):
    parsed = _parse_date(value)

    if parsed is None:
        return None

    return parsed.isoformat()


def _add_months(source_date, months=1):
    """
    Add calendar months while preserving the day whenever possible.

    Example:
        10 Jul 2026 + 1 month = 10 Aug 2026
    """

    month_index = source_date.month - 1 + months
    year = source_date.year + month_index // 12
    month = month_index % 12 + 1

    day = min(
        source_date.day,
        calendar.monthrange(year, month)[1],
    )

    return date(year, month, day)


def _months_inclusive(start_date, end_date):
    """
    Count calendar EMI dates inclusively.

    10 Jul 2026 -> 10 Dec 2026 = 6
    """

    if start_date > end_date:
        return 0

    return (
        (end_date.year - start_date.year) * 12
        + (end_date.month - start_date.month)
        + 1
    )


# ============================================================
# LOAN PAYLOAD NORMALIZATION
# ============================================================

def _normalize_loan_payload(payload):
    """
    Convert the FleetDoc frontend loan fields into the canonical
    Loan database fields.

    Frontend fields supported:

        vehicle
        financerBank / bank
        loanAmount / amount / principal
        monthlyAmount
        interestRate
        durationType
        loanDuration
        tenureMonths
        emiStartDate / startDate
        emiClosingDate / closingDate
        loanNumber

    The original frontend fields are also preserved in `data`.
    """

    source = dict(payload or {})
    data = dict(source.get("data") or {})

    # Preserve all original frontend fields inside data.
    for key, value in source.items():
        if key != "data":
            data[key] = value

    vehicle = (
        source.get("vehicle")
        or source.get("vehicleNo")
        or source.get("vehicleNumber")
        or ""
    )

    bank = (
        source.get("bank")
        or source.get("financerBank")
        or source.get("bankName")
    )

    principal = _to_float(
        source.get(
            "principal",
            source.get(
                "loanAmount",
                source.get("amount", 0),
            ),
        )
    )

    monthly_amount = _to_float(
        source.get(
            "monthlyAmount",
            source.get("monthly_amount", 0),
        )
    )

    interest_rate = _to_float(
        source.get(
            "interestRate",
            source.get("interest_rate", 0),
        )
    )

    duration_type = str(
        source.get(
            "durationType",
            source.get("duration_type", "months"),
        )
        or "months"
    ).strip().lower()

    # Accept several frontend spellings.
    if duration_type in {
        "daterange",
        "date-range",
        "date_range",
        "range",
    }:
        duration_type = "dateRange"
    else:
        duration_type = "months"

    raw_duration = source.get(
        "loanDuration",
        source.get("tenureMonths", source.get("tenure_months", 0)),
    )

    # If an old frontend accidentally sends loanDuration="dateRange",
    # do not use that as the numeric tenure.
    if isinstance(raw_duration, str) and raw_duration.strip().lower() in {
        "daterange",
        "date-range",
        "date_range",
        "range",
    }:
        raw_duration = 0

    tenure_months = _to_int(raw_duration)

    start_value = source.get(
        "emiStartDate",
        source.get(
            "startDate",
            source.get("start_date"),
        ),
    )

    closing_value = source.get(
        "emiClosingDate",
        source.get(
            "closingDate",
            source.get("closing_date"),
        ),
    )

    start_date = _parse_date(start_value)
    closing_date = _parse_date(closing_value)

    # Date-range mode determines the number of EMI records from the
    # selected start/end dates.
    if duration_type == "dateRange":
        if start_date and closing_date:
            tenure_months = _months_inclusive(
                start_date,
                closing_date,
            )
        else:
            tenure_months = 0

    # For fixed-month mode, closing date is calculated from the
    # start date and number of months when possible.
    elif start_date and tenure_months > 0:
        closing_date = _add_months(start_date, tenure_months - 1)

    # If monthly EMI was not supplied, calculate it.
    #
    # With interest:
    #     standard reducing-balance EMI formula
    #
    # Without interest:
    #     principal / number of EMI records
    if monthly_amount <= 0 and principal > 0 and tenure_months > 0:
        if interest_rate > 0:
            monthly_rate = interest_rate / 12 / 100
            factor = (1 + monthly_rate) ** tenure_months

            if factor != 1:
                monthly_amount = (
                    principal
                    * monthly_rate
                    * factor
                    / (factor - 1)
                )
        else:
            monthly_amount = principal / tenure_months

    loan_number = (
        source.get("loanNumber")
        or source.get("loan_number")
    )

    return {
        "vehicle": str(vehicle).strip(),
        "bank": str(bank).strip() if bank is not None else None,
        "principal": principal,
        "monthly_amount": monthly_amount,
        "interest_rate": interest_rate,
        "tenure_months": tenure_months,
        "start_date": start_date.isoformat() if start_date else None,
        "closing_date": closing_date.isoformat() if closing_date else None,
        "status": str(source.get("status") or "Active"),
        "data": data,
        "duration_type": duration_type,
        "loan_number": loan_number,
        "emi_start_date": start_date,
        "emi_closing_date": closing_date,
    }


# ============================================================
# EMI GENERATION
# ============================================================

def _build_emi_rows(loan):
    """
    Generate EMI rows for one loan.

    Mode 1:
        durationType = months
        loanDuration = 60
        -> exactly 60 EMI records

    Mode 2:
        durationType = dateRange
        start = 10-07-2026
        end   = 10-12-2026
        -> exactly 6 EMI records

    Both start and end dates are included.
    """

    data = dict(loan.data or {})

    duration_type = str(
        data.get("durationType", "months") or "months"
    ).strip().lower()

    if duration_type in {
        "daterange",
        "date-range",
        "date_range",
        "range",
    }:
        duration_type = "dateRange"
    else:
        duration_type = "months"

    start_date = _parse_date(
        data.get("emiStartDate")
        or loan.start_date
        or data.get("startDate")
    )

    end_date = _parse_date(
        data.get("emiClosingDate")
        or loan.closing_date
        or data.get("closingDate")
    )

    # Recover frontend loanAmount/monthlyAmount if an older record
    # was saved before normalization.
    principal = _to_float(
        loan.principal
        if loan.principal
        else data.get(
            "loanAmount",
            data.get("amount", 0),
        )
    )

    monthly_amount = _to_float(
        loan.monthly_amount
        if loan.monthly_amount
        else data.get("monthlyAmount", 0)
    )

    interest_rate = _to_float(
        loan.interest_rate
        if loan.interest_rate
        else data.get("interestRate", 0)
    )

    tenure_months = _to_int(
        loan.tenure_months
        if loan.tenure_months
        else data.get("loanDuration", 0)
    )

    if duration_type == "dateRange":
        if not start_date or not end_date:
            return []

        if start_date > end_date:
            return []

        tenure_months = _months_inclusive(
            start_date,
            end_date,
        )

    else:
        if tenure_months <= 0:
            return []

        if not start_date:
            return []

        # Fixed tenure mode always creates exactly N EMI dates.
        end_date = _add_months(
            start_date,
            tenure_months - 1,
        )

    if monthly_amount <= 0 and principal > 0:
        if interest_rate > 0:
            monthly_rate = interest_rate / 12 / 100
            factor = (1 + monthly_rate) ** tenure_months

            if factor != 1:
                monthly_amount = (
                    principal
                    * monthly_rate
                    * factor
                    / (factor - 1)
                )
        else:
            monthly_amount = principal / tenure_months

    if monthly_amount <= 0:
        return []

    rows = []

    current_date = start_date
    generated = 0

    while generated < tenure_months:
        if current_date > end_date:
            break

        rows.append(
            {
                "loan_id": loan.id,
                "vehicle": loan.vehicle,
                "bank": loan.bank,
                "due": current_date.isoformat(),
                "amount": round(monthly_amount, 2),
                "status": "Pending",
                "paid_date": None,
                "data": {
                    "loanId": loan.id,
                    "durationType": duration_type,
                    "emiNumber": generated + 1,
                    "totalEmis": tenure_months,
                    "principal": principal,
                    "monthlyAmount": round(monthly_amount, 2),
                    "interestRate": interest_rate,
                },
            }
        )

        generated += 1
        current_date = _add_months(
            start_date,
            generated,
        )

    return rows


def _generate_emis_for_loan(db, loan):
    """
    Create the EMI schedule for a loan only when the loan does not
    already have EMI records.

    The loan's JSON data also stores ``emiScheduleInitialized``.
    That flag is important because an intentionally deleted EMI
    schedule must NOT be recreated by the compatibility sync.
    """

    existing = (
        db.query(EMI)
        .filter(EMI.loan_id == loan.id)
        .count()
    )

    if existing > 0:
        return []

    rows = _build_emi_rows(loan)

    if not rows:
        return []

    created = []

    for row in rows:
        emi = EMI(**row)
        db.add(emi)
        created.append(emi)

    return created


def _mark_emi_schedule_initialized(loan):
    """Mark a loan as having an intentionally initialized EMI schedule."""
    data = dict(loan.data or {})
    data["emiScheduleInitialized"] = True
    loan.data = data


def _sync_missing_loan_emis(db):
    """
    Repair legacy loans that pre-date automatic EMI generation.

    IMPORTANT: this must only run for loans whose EMI schedule has
    never been initialized. Once a schedule has been created, the
    ``emiScheduleInitialized`` flag remains true even if the user
    intentionally deletes some or all EMI records. This prevents the
    deleted EMI records from coming back on the next GET /emis.
    """

    loans = db.query(Loan).order_by(Loan.id.asc()).all()
    changed = False

    for loan in loans:
        data = dict(loan.data or {})

        # Already initialized means the current EMI state is authoritative.
        # Never regenerate records merely because the user deleted them.
        if data.get("emiScheduleInitialized") is True:
            continue

        existing = (
            db.query(EMI)
            .filter(EMI.loan_id == loan.id)
            .count()
        )

        if existing > 0:
            # Legacy loan already has a schedule. Remember that fact so
            # future intentional deletions are not repaired automatically.
            _mark_emi_schedule_initialized(loan)
            changed = True
            continue

        created = _generate_emis_for_loan(db, loan)

        if created:
            _mark_emi_schedule_initialized(loan)
            changed = True

    if changed:
        db.commit()


# ============================================================
# DASHBOARD
# ============================================================

@router.get("/dashboard")
def dashboard(
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    return {
        "vehicles": db.query(Vehicle).count(),
        "documents": db.query(Document).count(),
        "emis": db.query(EMI).filter(EMI.status != "Paid").count(),
        "challans": db.query(Challan).filter(Challan.status != "Paid").count(),
        "roadTaxes": db.query(RoadTax).count(),
        "notifications": db.query(Notification)
        .filter(
            Notification.user_id == user.id,
            Notification.status == "unread",
        )
        .count(),
    }


# ============================================================
# AUDIT LOGS
# ============================================================

def _audit_module(entity: str | None, details: dict | None = None) -> str:
    """Convert database entity names into the labels used by the UI."""
    value = str(entity or "").strip()
    mapping = {
        "vehicles": "Vehicles",
        "documents": "Documents",
        "emis": "EMI",
        "loans": "EMI",
        "challans": "Challans",
        "road_taxes": "Road Tax",
        "users": "Users",
        "Settings": "Settings",
        "Authentication": "Authentication",
        "notifications": "Notifications",
        "subscriptions": "Premium",
        "payments": "Payments",
    }
    if value in mapping:
        return mapping[value]
    if value:
        return value.replace("_", " ").title()
    return "System"


def _audit_action(action: str | None) -> str:
    mapping = {
        "create": "Created",
        "update": "Updated",
        "delete": "Deleted",
        "settings_updated": "Settings Updated",
        "login": "Signed In",
        "login_2fa_requested": "2FA Code Requested",
        "login_2fa_verified": "2FA Verified",
        "password_change": "Password Changed",
        "password_reset": "Password Reset",
    }
    value = str(action or "").strip()
    return mapping.get(value, value.replace("_", " ").title() or "Activity")


def _audit_out(row, user=None):
    """Return both canonical API fields and the legacy UI field names."""
    created = row.created_at.isoformat() if row.created_at else None
    resolved_user = user
    if resolved_user is None and getattr(row, "user", None):
        resolved_user = row.user

    user_name = resolved_user.name if resolved_user else None
    user_email = resolved_user.email if resolved_user else None
    module = _audit_module(row.entity, row.details or {})
    action = _audit_action(row.action)

    return {
        "id": row.id,
        "userId": row.user_id,
        "userName": user_name,
        "userEmail": user_email,
        "user": user_name,
        "action": action,
        "actionKey": row.action,
        "entity": row.entity,
        "entityId": row.entity_id,
        "module": module,
        "description": (row.details or {}).get("description", ""),
        "details": row.details or {},
        "createdAt": created,
        "timestamp": created,
        "time": created,
    }


@router.get("/audit-logs")
def get_audit_logs(
    limit: int = Query(500, ge=1, le=2000),
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    if user.role != "Admin" and not (user.permissions or {}).get("settings", {}).get("view"):
        raise HTTPException(403, "Audit log permission denied")

    rows = (
        db.query(AuditLog)
        .order_by(AuditLog.created_at.desc(), AuditLog.id.desc())
        .limit(limit)
        .all()
    )
    # Avoid requiring a relationship on AuditLog; resolve users once.
    user_ids = {r.user_id for r in rows if r.user_id is not None}
    users_by_id = {}
    if user_ids:
        from app.models.models import User
        users_by_id = {u.id: u for u in db.query(User).filter(User.id.in_(user_ids)).all()}
    return [_audit_out(row, users_by_id.get(row.user_id)) for row in rows]


@router.delete("/audit-logs")
def delete_audit_logs(
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    if user.role != "Admin":
        raise HTTPException(403, "Only Admin can clear audit logs")

    count = db.query(AuditLog).delete(synchronize_session=False)
    # Record the clear action cannot be kept in the same table after deletion,
    # so it is intentionally not re-added.
    db.commit()
    return {"message": "Audit logs cleared successfully", "deleted": count}


# ============================================================
# LIST
# ============================================================

@router.get("/{collection}")
def list_collection(
    collection: str,
    q: str | None = None,
    page: int = 1,
    limit: int = 100,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    if collection not in MODEL_MAP:
        raise HTTPException(404, "Resource not found")

    # Important:
    # Repair loans created by the previous backend version.
    # This means existing loans can start showing EMI records
    # without the user having to recreate them.
    if collection == "emis":
        _sync_missing_loan_emis(db)

    Model = MODEL_MAP[collection]
    query = db.query(Model)

    if q:
        fields = [
            c
            for c in (
                "number",
                "vehicle",
                "type",
                "status",
                "owner",
                "bank",
                "email",
            )
            if hasattr(Model, c)
        ]

        if fields:
            from sqlalchemy import or_

            query = query.filter(
                or_(
                    *[
                        getattr(Model, field).ilike(f"%{q}%")
                        for field in fields
                    ]
                )
            )

    rows = (
        query.order_by(Model.id.desc())
        .offset((page - 1) * limit)
        .limit(min(limit, 500))
        .all()
    )

    return [SERIAL[collection](x) for x in rows]


# ============================================================
# CREATE
# ============================================================

@router.post("/{collection}")
def create_collection(
    collection: str,
    payload: dict,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    if collection not in MODEL_MAP:
        raise HTTPException(404, "Resource not found")

    if not allowed(user, collection, "add", db):
        raise HTTPException(403, "Permission denied")

    Model = MODEL_MAP[collection]

    # --------------------------------------------------------
    # SPECIAL LOAN HANDLING
    # --------------------------------------------------------
    if collection == "loans":
        normalized = _normalize_loan_payload(payload)

        if not normalized["vehicle"]:
            raise HTTPException(
                422,
                "Vehicle is required for a loan",
            )

        if normalized["principal"] <= 0:
            raise HTTPException(
                422,
                "Loan amount must be greater than 0",
            )

        if normalized["monthly_amount"] <= 0:
            raise HTTPException(
                422,
                "Monthly EMI amount could not be determined",
            )

        if not normalized["emi_start_date"]:
            raise HTTPException(
                422,
                "EMI start date is required",
            )

        if normalized["duration_type"] == "dateRange":
            if not normalized["emi_closing_date"]:
                raise HTTPException(
                    422,
                    "EMI closing date is required for date range mode",
                )

            if normalized["emi_start_date"] > normalized["emi_closing_date"]:
                raise HTTPException(
                    422,
                    "EMI closing date must be on or after the start date",
                )

            normalized["tenure_months"] = _months_inclusive(
                normalized["emi_start_date"],
                normalized["emi_closing_date"],
            )

        else:
            if normalized["tenure_months"] <= 0:
                raise HTTPException(
                    422,
                    "Loan duration must be greater than 0 months",
                )

            # Make sure the closing date exists for fixed-month loans.
            if not normalized["closing_date"]:
                normalized["closing_date"] = _add_months(
                    normalized["emi_start_date"],
                    normalized["tenure_months"] - 1,
                ).isoformat()

        loan_data = dict(normalized["data"])

        # Keep these values available to the frontend exactly as it
        # already uses them.
        loan_data["durationType"] = normalized["duration_type"]
        loan_data["loanAmount"] = normalized["principal"]
        loan_data["monthlyAmount"] = normalized["monthly_amount"]
        loan_data["interestRate"] = normalized["interest_rate"]
        loan_data["loanDuration"] = (
            normalized["tenure_months"]
            if normalized["duration_type"] == "months"
            else "dateRange"
        )

        if normalized["loan_number"] is not None:
            loan_data["loanNumber"] = normalized["loan_number"]

        if normalized["emi_start_date"]:
            loan_data["emiStartDate"] = normalized["emi_start_date"].isoformat()

        if normalized["emi_closing_date"]:
            loan_data["emiClosingDate"] = normalized["emi_closing_date"].isoformat()

        # financerBank is the field used by the current frontend.
        if normalized["bank"]:
            loan_data["financerBank"] = normalized["bank"]

        obj = Loan(
            vehicle=normalized["vehicle"],
            bank=normalized["bank"],
            principal=normalized["principal"],
            monthly_amount=normalized["monthly_amount"],
            interest_rate=normalized["interest_rate"],
            tenure_months=normalized["tenure_months"],
            start_date=normalized["start_date"],
            closing_date=normalized["closing_date"],
            status=normalized["status"],
            data=loan_data,
        )

        db.add(obj)

        try:
            db.flush()

            # Generate all EMI records before committing the loan.
            created_emis = _generate_emis_for_loan(db, obj)

            if not created_emis:
                raise HTTPException(
                    422,
                    "No EMI records could be generated from the selected loan dates and duration",
                )

            # The schedule has now been deliberately created for this loan.
            # Keep this flag so deleting EMI records later is respected and
            # the legacy compatibility sync does not recreate them.
            _mark_emi_schedule_initialized(obj)

            db.commit()
            db.refresh(obj)

        except HTTPException:
            db.rollback()
            raise

        except IntegrityError:
            db.rollback()
            raise HTTPException(
                409,
                "Duplicate or invalid loan record",
            )

        except Exception:
            db.rollback()
            raise

        db.add(
            AuditLog(
                user_id=user.id,
                action="create",
                entity=Loan.__tablename__,
                entity_id=str(obj.id),
                details={
                    "emiCount": len(created_emis),
                    "durationType": normalized["duration_type"],
                },
            )
        )

        db.commit()

        return SERIAL[collection](obj)

    # --------------------------------------------------------
    # NORMAL RESOURCES
    # --------------------------------------------------------

    obj = Model(**clean_payload(payload, Model))

    db.add(obj)

    try:
        db.commit()
        db.refresh(obj)

    except IntegrityError:
        db.rollback()
        raise HTTPException(
            409,
            "Duplicate or invalid record",
        )

    db.add(
        AuditLog(
            user_id=user.id,
            action="create",
            entity=Model.__tablename__,
            entity_id=str(obj.id),
            details={},
        )
    )

    db.commit()

    return SERIAL[collection](obj)


# ============================================================
# UPDATE
# ============================================================

@router.patch("/{collection}/{item_id}")
def update_collection(
    collection: str,
    item_id: int,
    payload: dict,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    if collection not in MODEL_MAP:
        raise HTTPException(404, "Resource not found")

    if not allowed(user, collection, "edit", db):
        raise HTTPException(403, "Permission denied")

    Model = MODEL_MAP[collection]
    obj = db.get(Model, item_id)

    if not obj:
        raise HTTPException(404, "Record not found")

    # --------------------------------------------------------
    # SPECIAL LOAN UPDATE
    # --------------------------------------------------------
    if collection == "loans":
        # Rebuild the complete loan payload from the existing
        # database record + incoming frontend fields.
        current = {
            "vehicle": obj.vehicle,
            "bank": obj.bank,
            "principal": obj.principal,
            "monthlyAmount": obj.monthly_amount,
            "interestRate": obj.interest_rate,
            "tenureMonths": obj.tenure_months,
            "startDate": obj.start_date,
            "closingDate": obj.closing_date,
            "status": obj.status,
            **(obj.data or {}),
        }

        current.update(payload or {})

        normalized = _normalize_loan_payload(current)

        if not normalized["vehicle"]:
            raise HTTPException(422, "Vehicle is required for a loan")

        if normalized["principal"] <= 0:
            raise HTTPException(422, "Loan amount must be greater than 0")

        if normalized["monthly_amount"] <= 0:
            raise HTTPException(
                422,
                "Monthly EMI amount could not be determined",
            )

        if not normalized["emi_start_date"]:
            raise HTTPException(
                422,
                "EMI start date is required",
            )

        if normalized["duration_type"] == "dateRange":
            if not normalized["emi_closing_date"]:
                raise HTTPException(
                    422,
                    "EMI closing date is required for date range mode",
                )

            if normalized["emi_start_date"] > normalized["emi_closing_date"]:
                raise HTTPException(
                    422,
                    "EMI closing date must be on or after the start date",
                )

            normalized["tenure_months"] = _months_inclusive(
                normalized["emi_start_date"],
                normalized["emi_closing_date"],
            )

        else:
            if normalized["tenure_months"] <= 0:
                raise HTTPException(
                    422,
                    "Loan duration must be greater than 0 months",
                )

            normalized["closing_date"] = _add_months(
                normalized["emi_start_date"],
                normalized["tenure_months"] - 1,
            ).isoformat()

        # Delete the previous EMI schedule because the loan schedule
        # has changed.
        db.query(EMI).filter(EMI.loan_id == obj.id).delete(
            synchronize_session=False
        )

        obj.vehicle = normalized["vehicle"]
        obj.bank = normalized["bank"]
        obj.principal = normalized["principal"]
        obj.monthly_amount = normalized["monthly_amount"]
        obj.interest_rate = normalized["interest_rate"]
        obj.tenure_months = normalized["tenure_months"]
        obj.start_date = normalized["start_date"]
        obj.closing_date = normalized["closing_date"]
        obj.status = normalized["status"]

        loan_data = dict(normalized["data"])
        loan_data["durationType"] = normalized["duration_type"]
        loan_data["loanAmount"] = normalized["principal"]
        loan_data["monthlyAmount"] = normalized["monthly_amount"]
        loan_data["interestRate"] = normalized["interest_rate"]
        loan_data["loanDuration"] = (
            normalized["tenure_months"]
            if normalized["duration_type"] == "months"
            else "dateRange"
        )

        if normalized["loan_number"] is not None:
            loan_data["loanNumber"] = normalized["loan_number"]

        if normalized["emi_start_date"]:
            loan_data["emiStartDate"] = normalized["emi_start_date"].isoformat()

        if normalized["emi_closing_date"]:
            loan_data["emiClosingDate"] = normalized["emi_closing_date"].isoformat()

        if normalized["bank"]:
            loan_data["financerBank"] = normalized["bank"]

        obj.data = loan_data

        db.flush()

        created_emis = _generate_emis_for_loan(db, obj)

        if not created_emis:
            db.rollback()
            raise HTTPException(
                422,
                "No EMI records could be generated from the updated loan",
            )

        # The updated loan now has a fresh, authoritative EMI schedule.
        _mark_emi_schedule_initialized(obj)

        db.commit()
        db.refresh(obj)

        return SERIAL[collection](obj)

    # --------------------------------------------------------
    # NORMAL UPDATE
    # --------------------------------------------------------

    for key, value in clean_payload(payload, Model).items():
        setattr(obj, key, value)

    db.commit()
    db.refresh(obj)

    return SERIAL[collection](obj)


# # ============================================================
# # DELETE
# # ============================================================

# @router.delete("/{collection}/{item_id}")
# def delete_collection(
#     collection: str,
#     item_id: int,
#     db: Session = Depends(get_db),
#     user=Depends(get_current_user),
# ):
#     if collection not in MODEL_MAP:
#         raise HTTPException(404, "Resource not found")

#     if not allowed(user, collection, "delete", db):
#         raise HTTPException(403, "Permission denied")

#     Model = MODEL_MAP[collection]
#     obj = db.get(Model, item_id)

#     if not obj:
#         raise HTTPException(404, "Record not found")

#     db.delete(obj)
#     db.commit()

#     return {"message": "Record deleted"}

# ============================================================
# DELETE
# ============================================================

@router.delete("/{collection}/{item_id}")
def delete_collection(
    collection: str,
    item_id: int,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    if collection not in MODEL_MAP:
        raise HTTPException(404, "Resource not found")

    if not allowed(user, collection, "delete", db):
        raise HTTPException(403, "Permission denied")

    Model = MODEL_MAP[collection]
    obj = db.get(Model, item_id)

    if not obj:
        raise HTTPException(404, "Record not found")

    deleted_emi_count = 0

    try:
        # ----------------------------------------------------
        # LOAN DELETE
        # ----------------------------------------------------
        # A loan can have multiple EMI records.
        # The database relationship currently uses
        # ON DELETE SET NULL, so deleting the loan alone
        # does NOT delete its EMI records.
        #
        # Therefore, delete all EMIs belonging to this loan
        # before deleting the loan itself.
        # ----------------------------------------------------

        if collection == "loans":
            deleted_emi_count = (
                db.query(EMI)
                .filter(EMI.loan_id == obj.id)
                .delete(
                    synchronize_session=False
                )
            )

        # ----------------------------------------------------
        # DELETE MAIN RECORD
        # ----------------------------------------------------

        deleted_id = obj.id

        db.delete(obj)

        # Flush before creating the audit record.
        db.flush()

        # ----------------------------------------------------
        # AUDIT LOG
        # ----------------------------------------------------

        db.add(
            AuditLog(
                user_id=user.id,
                action="delete",
                entity=Model.__tablename__,
                entity_id=str(deleted_id),
                details={
                    "collection": collection,
                    "deletedEmis": deleted_emi_count,
                },
            )
        )

        db.commit()

        return {
            "message": "Record deleted successfully",
            "id": deleted_id,
            "collection": collection,
            "deletedEmis": deleted_emi_count,
        }

    except IntegrityError:
        db.rollback()

        raise HTTPException(
            status_code=409,
            detail=(
                "This record cannot be deleted because it is "
                "still referenced by other data."
            ),
        )

    except Exception:
        db.rollback()
        raise

# ============================================================
# EMI PAYMENT
# ============================================================

@router.post("/emis/{item_id}/pay")
def pay_emi(
    item_id: int,
    payload: dict | None = None,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    if not allowed(user, "emis", "paid", db):
        raise HTTPException(
            403,
            "Payment permission denied",
        )

    x = db.get(EMI, item_id)

    if not x:
        raise HTTPException(
            404,
            "EMI not found",
        )

    x.status = "Paid"
    x.paid_date = (
        (payload or {}).get("paidDate")
        or datetime.now().strftime("%d %b %Y")
    )

    db.commit()

    return emi_out(x)


# ============================================================
# CHALLAN PAYMENT
# ============================================================

@router.post("/challans/{item_id}/pay")
def pay_challan(
    item_id: int,
    payload: dict | None = None,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    if not allowed(user, "challans", "paid", db):
        raise HTTPException(
            403,
            "Payment permission denied",
        )

    x = db.get(Challan, item_id)

    if not x:
        raise HTTPException(
            404,
            "Challan not found",
        )

    x.status = "Paid"
    x.payment_date = (
        (payload or {}).get("paymentDate")
        or datetime.now().strftime("%d %b %Y")
    )

    db.commit()

    return challan_out(x)


# ============================================================
# SETTINGS
# ============================================================

@router.get("/settings/global")
def get_settings(
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    s = (
        db.query(Setting)
        .filter(Setting.key == "global")
        .first()
    )

    return s.value if s else {}


@router.put("/settings/global")
def update_settings(
    payload: dict,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    if user.role != "Admin" and not (
        user.permissions or {}
    ).get("settings", {}).get("edit"):
        raise HTTPException(
            403,
            "Settings permission denied",
        )

    s = (
        db.query(Setting)
        .filter(Setting.key == "global")
        .first()
    )

    if not s:
        s = Setting(
            key="global",
            value={},
        )
        db.add(s)

    s.value = payload
    db.add(
        AuditLog(
            user_id=user.id,
            action="settings_updated",
            entity="Settings",
            entity_id=str(s.id),
            details={
                "security": {
                    "two_factor": bool(payload.get("twoFactorAuthentication", payload.get("twoFactor", False))),
                    "strong_password": bool(payload.get("strongPasswordRequired", payload.get("strongPassword", True))),
                    "session_timeout": payload.get("sessionTimeout"),
                },
            },
        )
    )
    db.commit()

    return s.value



# ============================================================
# NOTIFICATIONS
# ============================================================

@router.get("/notifications/me")
def notifications(
    unread_only: bool = False,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    q = db.query(Notification).filter(
        Notification.user_id == user.id
    )

    if unread_only:
        q = q.filter(
            Notification.status == "unread"
        )

    return [
        {
            "id": n.id,
            "title": n.title,
            "message": n.message,
            "type": n.type,
            "channel": n.channel,
            "status": n.status,
            "createdAt": n.created_at.isoformat(),
        }
        for n in q.order_by(
            Notification.created_at.desc()
        ).limit(200)
    ]


@router.patch("/notifications/{item_id}/read")
def mark_read(
    item_id: int,
    db: Session = Depends(get_db),
    user=Depends(get_current_user),
):
    n = db.get(Notification, item_id)

    if not n or n.user_id != user.id:
        raise HTTPException(
            404,
            "Notification not found",
        )

    n.status = "read"
    db.commit()

    return {"message": "Notification marked as read"}
